### PR TITLE
Added HiNT

### PR DESCRIPTION
**Pull request by LPardue**
The proposed slot for Lucas is actually a two-hander: Lucas will talk about HiNT and Ben will talk about HELIUM.

### CODE REVIEW

**Comment by mnot** [comment]
40 minutes seems like too much; can we give them 10 minutes each?

**Comment by LPardue** [comment]
That was my intention, but more like 5 minute per hand and 10 minutes for Q&A for a total of 20

**Comment by mnot** [comment]
OK, I'll adjust.

**Comment by mnot** [comment]
Never mind, I misread the PR - sorry.

**Pull request merged**
